AWSTemplateFormatVersion: 2010-09-09
Parameters:
  InstanceDBHost:
    Description: IP Address Host EC2
    Type: String  
Resources:  
  taskdefinitiondb:
    Type: 'AWS::ECS::TaskDefinition'
    DependsOn:
      - ECSAluraExecutionRole
      - ECSAluraTaskRole
    Properties:
      TaskRoleArn: !Ref ECSAluraTaskRole
      ExecutionRoleArn: !Ref ECSAluraExecutionRole
      ContainerDefinitions:
        - Name: db          
          Essential: 'true'
          Image: postgres
          MemoryReservation: 128
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: 'True'
              awslogs-group: db-postgresql-logs
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: postgres
          PortMappings:
            - ContainerPort: 5432
              HostPort: 5432
          Environment:
            - Name: POSTGRES_DB
              Value: 'postgres'
            - Name: POSTGRES_USER
              Value: 'postgres'
            - Name: POSTGRES_PASSWORD
              Value: 'postgres'
      NetworkMode: bridge
  taskdefinitionweb:
    Type: 'AWS::ECS::TaskDefinition'
    DependsOn:
      - ECSAluraExecutionRole
      - ECSAluraTaskRole
    Properties:
      TaskRoleArn: !Ref ECSAluraTaskRole
      ExecutionRoleArn: !Ref ECSAluraExecutionRole
      ContainerDefinitions:
        - Name: webapp-aluraflix          
          Essential: 'true'
          Image: albertosouzafernandes/alurachallengedevops
          MemoryReservation: 128
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: 'True'
              awslogs-group: aluraflix-logs
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: challenge-devops
          PortMappings:
            - ContainerPort: 8000
              HostPort: 8000
          Environment:
            - Name: POSTGRES_DB
              Value: 'postgres'
            - Name: POSTGRES_USER
              Value: 'postgres'
            - Name: POSTGRES_PASSWORD
              Value: 'postgres'
            - Name: POSTGRES_HOST
              Value: !Ref InstanceDBHost  
            - Name: DJANGO_SUPERUSER_EMAIL
              Value: 'root@asf.tec.br'
            - Name: DJANGO_SUPERUSER_PASSWORD
              Value: 'pass123'
      NetworkMode: bridge
  servicedb:
    Type: 'AWS::ECS::Service'
    DependsOn:
      - taskdefinitiondb
    Properties:
      Cluster: ClusterAluraChallengeDevOps-ECSCluster-3nbkKFvSrSOy
      DesiredCount: '1'
      TaskDefinition: !Ref taskdefinitiondb
  AluraChallengeDevOpsWebApp:
    Type: 'AWS::ECS::Service'
    DependsOn:
      - taskdefinitionweb
    Properties:
      Cluster: ClusterAluraChallengeDevOps-ECSCluster-3nbkKFvSrSOy
      DesiredCount: '1'
      TaskDefinition: !Ref taskdefinitionweb
  ECSAluraExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
  ECSAluraTaskRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
Outputs:
  ecsservice:
    Value: !Ref servicedb
  taskdef:
    Value: !Ref taskdefinitiondb