AWSTemplateFormatVersion: 2010-09-09  
Resources:  
  taskdefinitiondb:
    Type: 'AWS::ECS::TaskDefinition'
    DependsOn:
      - ECSAluraExecutionRoleDB
      - ECSAluraTaskRoleDB
    Properties:
      TaskRoleArn: !Ref ECSAluraTaskRoleDB
      ExecutionRoleArn: !Ref ECSAluraExecutionRoleDB
      ContainerDefinitions:
        - Name: db          
          Essential: 'true'
          Image: postgres
          MemoryReservation: 128
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: 'True'
              awslogs-group: db-postgresql-logs
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: postgres
          PortMappings:
            - ContainerPort: 5432
              HostPort: 5432
          Environment:
            - Name: POSTGRES_DB
              Value: 'postgres'
            - Name: POSTGRES_USER
              Value: 'postgres'
            - Name: POSTGRES_PASSWORD
              Value: 'postgres'
      NetworkMode: bridge
  servicedb:
    Type: 'AWS::ECS::Service'
    DependsOn:
      - taskdefinitiondb
    Properties:
      Cluster: ClusterAluraChallengeDevOps-ECSCluster-3nbkKFvSrSOy
      DesiredCount: '1'
      TaskDefinition: !Ref taskdefinitiondb
  ECSAluraExecutionRoleDB:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
  ECSAluraTaskRoleDB:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
Outputs:
  ecsservice:
    Value: !Ref servicedb
  taskdef:
    Value: !Ref taskdefinitiondb